### List all the messages
GET http://localhost:5000/messages

### Create a new message

POST http://localhost:5000/messages
content-type: application/json

{
    "content": "luttuce"
}

### Fetch a message

GET http://localhost:5000/messages/12?q=h2o&test=tt