### List all the messages
GET http://localhost:5000/messages

### Create a new message

POST http://localhost:5000/messages
content-type: application/json

{
    "content": "Hi There"
}

### Fetch a message

GET http://localhost:5000/messages/33?q=h2o&test=tt